### ISSUE TITLE
how to solve this problem(.h)?

### ISSUE THREAD

**Issue by lwy-599** [UCI-CARL/CARLsim6#10]
PLATFORM: ubuntu CARLsim6
Tutorial/5_motion_energy   still can't find motion_energy.h.
Tutorial/4_image_process   still can't find carlsim_confi_api_.h.

![QQ图片20220615094120](https://user-images.githubusercontent.com/32786740/173718536-e3b62f86-771b-4cbe-b70c-463538d5c30f.png)
![QQ图片20220615094426](https://user-images.githubusercontent.com/32786740/173718552-154c1262-7403-4f53-ad9e-250d39033f4c.png)

**Comment by larsnm** [comment]
The user tried to build with an obsolete makefile. 
This will be cleansed with fixpack 2 that will be published in the upcoming weeks.
