### ISSUE TITLE
Error loading libcarlsim-stopwatch.so when running the samples

### ISSUE THREAD

**Issue by Runkli** [UCI-CARL/CARLsim6#3]
After following the build steps, trying to run both benchmark and hello_world gives the following error:
```
./benchmark: error while loading shared libraries: libcarlsim-stopwatch.so: cannot open shared object file: No such file or directory
```
Noting that the build seemed to finish successfully without any errors. Any help would be appreciated

**Comment by Runkli** [comment]
I can find ```libcarlsim-stopwatch.so``` in carlsim6/lib directory though.

**Comment by Runkli** [comment]
Adding ```export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/carlsim6/lib/``` fixed it. Maybe the libraries aren't appended to PATH automatically upon build?

**Comment by bainro** [comment]
The parent CMakeLists.txt can have these two lines added near the top for the same effect:

```
set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib") 
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
```

Here's where I got the solution from: [Link](https://stackoverflow.com/questions/30398238/cmake-rpath-not-working-could-not-find-shared-object-file).
