### ISSUE TITLE
Must i have a Nvdia GPU and it's toolkit installed to build CARLsim6

### ISSUE THREAD

**Issue by efraser123** [UCI-CARL/CARLsim6#31]
I've attempted to build the library with the (-DCARLSIM_NO_CUDA=OFF)  option and the following error message is generated:
CMake Error at /usr/local/lib/python3.8/dist-packages/cmake/data/share/cmake-3.26/Modules/FindCUDA.cmake:861 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR

Thanks

**Comment by SigmaX** [comment]
@efraser123 You want to set `-DCARLSIM_NO_CUDA=ON` rather than `-DCARLSIM_NO_CUDA=OFF`.  The latter is a double negative :).

Note also that you'll probably also want to use `-DCARLSIM_PYCARL=OFF` (see https://github.com/UCI-CARL/CARLsim6/issues/22).

**Comment by efraser123** [comment]
Excellent! Thank you, Siggy.
Evan
